export interface RedirectRule {
  source: string
  destination: string
  permanent: boolean
}

/**
 * Redirect rules migrated from the old React site (redirectRoutes.tsx).
 * These are 301 permanent redirects for SEO preservation.
 * 
 * Total rules: 749
 * Excluded: 0 self-referencing, 357 duplicates, 9 already in next.config.ts
 */
export const redirectRules: RedirectRule[] = [
  { source: "/es/blog-es", destination: "/es/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/go-offline-on-whatsapp-without-turning-off-the-internet-how-to-use-whatsapp-proxy-setting-for-some-me-time", destination: "/blog/how-to-appear-offline-on-whatsapp", permanent: true },
  { source: "/how-to-create-a-chat-gpt-3-ai-chatbot-on-whatsapp", destination: "/", permanent: true },
  { source: "/blog/uncatogaries/how-to-send-bulk-messages-on-whatsapp", destination: "/", permanent: true },
  { source: "/blog/whatsapp-hacks/chatgpt-whatsapp-hacks/how-to-use-chatgpt-4-0-on-whatsapp", destination: "/", permanent: true },
  { source: "/form-page", destination: "/", permanent: true },
  { source: "/whatsapp-web-plus-alternatives-best-whatsapp-chrome-extension", destination: "/", permanent: true },
  { source: "/blog/whatsapp-hacks/chatgpt-4-0-on-whatsapp-install-the-latest-version-of-eazybe-chrome-extension-send-ai-whatsapp-messages-for-free", destination: "/", permanent: true },
  { source: "/home", destination: "/", permanent: true },
  { source: "/payment-done", destination: "/", permanent: true },
  { source: "/blog/whatsapp-hacks/how-to-set-birthday-reminders-on-whatsapp", destination: "/blog", permanent: true },
  { source: "/what-is-cataloug-in-whatsapp-business-how-to-make-and-maintain-it", destination: "/", permanent: true },
  { source: "/what-are-the-top-5-whatsapp-alternatives-for-2023", destination: "/", permanent: true },
  { source: "/inqury", destination: "/", permanent: true },
  { source: "/how-to-apply-for-green-tick-on-whatsapp-business", destination: "/", permanent: true },
  { source: "/blog/category/uncategorized", destination: "/blog", permanent: true },
  { source: "/integrations-pt/hubspot", destination: "/br/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/tag/whatsapp", destination: "/blog", permanent: true },
  { source: "/how-to-use-whatsapp-business-groups-and-broadcast-lists-to-reach-your-customers", destination: "/", permanent: true },
  { source: "/blog/whatsapp-hacks/chatgpt-4-0-on-whatsapp-latest-update-with-eazybe-chrome-extension-use-ai-messages-to-do-sales", destination: "/blog", permanent: true },
  { source: "/difference-between-whatsapp-whatsapp-business-api", destination: "/", permanent: true },
  { source: "/testimonials", destination: "/", permanent: true },
  { source: "/blog/growth/how-small-businesses-can-grow-in-2022/feed", destination: "/blog", permanent: true },
  { source: "/blog/2021/12/18", destination: "/blog", permanent: true },
  { source: "/blog/2022/03/28/sales-conversations-on-whatsapp/feed", destination: "/blog", permanent: true },
  { source: "/blog/exclusive/access-chatgpt-on-whatsapp-with-this-top-3-whatsapp-chrome-extensions-that-you-need-to-download-right-now", destination: "/blog", permanent: true },
  { source: "/a-complete-guide-to-the-whatsapp-business-api-price-list-for-2023", destination: "/", permanent: true },
  { source: "/blog/business/eazybe-chrome-extension-how-to-install-make-your-whatsapp-incredibly-professional-within-minutes/embed", destination: "/blog", permanent: true },
  { source: "/www.eazybe.com/integrations", destination: "/", permanent: true },
  { source: "/what-is-communities-in-whatsapp-interesting-ways-to-use-them", destination: "/", permanent: true },
  { source: "/blog/whatsapp/how-to-add-whatsapp-on-your-wordpress-website-free-plugins/feed", destination: "/blog", permanent: true },
  { source: "/blog/growth/use-these-7-proven-strategies-to-grow-your-business/feed", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-companion-mode-how-to-use-whatsapp-on-two-phones-with-same-number/feed", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/set-up-google-calendar-directly-on-your-whatsapp-with-eazybe-chrome-extension/feed", destination: "/blog", permanent: true },
  { source: "/blog/growth/sales-are-now-switching-to-messages/feed", destination: "/blog", permanent: true },
  { source: "/post/manage-google-calendar-through-eazybe-whatsapp-chrome-extensions-in-these-3-simple-steps", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/whatsapp-marketing/how-to-do-whatsapp-marketing-with-100-accurate-results-the-ultimate-guide-to-skyrocket-your-sales-with-eazybe", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/how-to-add-whatsapp-on-your-wordpress-website-free-plugins/post/%20add-whatsapp-on-your-wordpress-website", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/15-whatsapp-business-description-samples-templates-2023/feed", destination: "/blog", permanent: true },
  { source: "/blog/2022/04/15/sale-closing-plan-the-best-tool-to-close-almost-all-your-deals/feed", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/what-are-the-top-5-whatsapp-alternatives-for-2023", destination: "/blog", permanent: true },
  { source: "/blog/tag/howtosetremindersonwhatsapp/feed", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/how-to-edit-contacts-on-whatsapp-without-leaving-the-app-on-android-9-0-above-whatsapp-latest-update", destination: "/blog", permanent: true },
  { source: "/blog/category/growth", destination: "/blog", permanent: true },
  { source: "/blog/2022/04/06/how-whatapp-will-take-over-email-by-2030-change-is-coming", destination: "/blog", permanent: true },
  { source: "/blog/2022/04/06/how-whatapp-will-take-over-email-by-2030-change-is-coming/feed", destination: "/blog", permanent: true },
  { source: "/blog/tag/how-to-get-whatsapp-green-tick-for-free", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-business/what-is-cataloug-in-whatsapp-business-how-to-make-and-maintain-it", destination: "/blog", permanent: true },
  { source: "/blog/tag/what-is-whatsapp-broadcast-message/feed", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-business/what-is-communities-in-whatsapp-interesting-ways-to-use-them", destination: "/blog", permanent: true },
  { source: "/blog/tag/syncing-whatsapp-conversations-to-hubspot-crm", destination: "/blog", permanent: true },
  { source: "/blog/2023/04/10", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsapp-hubspot-integration-for-seamless-messaging/feed", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/how-to-synchronizing-whatsapp-conversations-with-hubspot-crmintegrated-crm-whatsapp-with-hubspot-setup-process-in-detail", destination: "/blog", permanent: true },
  { source: "/blog/tag/how-to-use-google-sheets-on-whatsapp", destination: "/google-sheets-whatsapp-integration", permanent: true },
  { source: "/blog/whatsapp/whatsapp-business/integrating-whatsapp-with-hubspot-syncing-whatsapp-chats", destination: "/blog", permanent: true },
  { source: "/blog/productivity/install-chrome-extension-in-microsoft-edge-use-this-hack", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-web-plus-alternatives-best-whatsapp-chrome-extension", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsapp-chatgpt/feed", destination: "/blog", permanent: true },
  { source: "/blog/growth/how-small-businesses-can-grow-in-2022", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-business/how-to-use-whatsapp-business-groups-and-broadcast-lists-to-reach-your-customers", destination: "/blog", permanent: true },
  { source: "/payment-unsuccessful", destination: "/blog", permanent: true },
  { source: "/blog/productivity/schedule-messages-in-whatsapp", destination: "/blog", permanent: true },
  { source: "/blog/growth/personalized-marketing-with-whatsapp/feed", destination: "/blog", permanent: true },
  { source: "/blog/tag/sync-whatsapp-contacts-on-hubspot/feed", destination: "/blog", permanent: true },
  { source: "/blog/uncategorized-en/how-to-send-bulk-messages-on-whatsapp", destination: "/blog", permanent: true },
  { source: "/blog/growth/make-your-texts-stand-out-with-these-whatsapp-message-tricks", destination: "/blog", permanent: true },
  { source: "/blog/2022/05/06/tutorial-how-to-organize-chats-using-labels/feed", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-business/how-to-get-whatsapp-green-tick-verification-in-2023-easiest-method/feed", destination: "/blog", permanent: true },
  { source: "/post/set-up-google-calendar-directly-on-your-whatsapp-with-eazybe-chrome-extension", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/how-to-apply-for-green-tick-on-whatsapp-business", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/set-reminders-on-whatsapp-with-eazybe-chrome-extension-a-complete-guide-to-setting-reminders-and-boosting-productivity/feed", destination: "/blog", permanent: true },
  { source: "//www.eazybe.com/integrations", destination: "/", permanent: true },
  { source: "/blog/whatsapp-hacks/set-up-google-calendar-directly-on-your-whatsapp-with-eazybe-chrome-extension", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsapp-green-tick", destination: "/blog", permanent: true },
  { source: "/blog/sales/sale-closing-plan-the-best-tool-to-close-almost-all-your-deals/feed", destination: "/blog", permanent: true },
  { source: "/post/how-to-add-whatsapp-on-your-wordpress-website-free-plugins", destination: "/blog", permanent: true },
  { source: "/blog/growth/use-these-7-proven-strategies-to-grow-your-business", destination: "/blog", permanent: true },
  { source: "/blog/growth/sales-are-now-switching-to-messages", destination: "/blog", permanent: true },
  { source: "/blog/customer-management/how-to-do-team-management-on-whatsapp-use-eazybe-chrome-extension-the-best-team-management-tool-online", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/difference-between-whatsapp-whatsapp-business-api", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/how-to-organize-chats-on-whatsapp-make-your-whatsapp-look-clean-with-eazybe-chrome-extension", destination: "/blog", permanent: true },
  { source: "/blog/customer-management/manage-your-hubspot-crm-on-whatsapp-with-eazybe-experience-real-time-changes-much-more", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/set-reminders-on-whatsapp-with-eazybe-chrome-extension-a-complete-guide-to-setting-reminders-and-boosting-productivity", destination: "/blog", permanent: true },
  { source: "/blog/chatgpt/how-to-create-a-chat-gpt-3-ai-chatbot-on-whatsapp", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/how-to-use-google-calendar-in-eazybe", destination: "/blog", permanent: true },
  { source: "/blog/brand-case-study/5-reasons-why-marketing-strategy-is-more-important-than-ever", destination: "/blog", permanent: true },
  { source: "/blog/sales/the-perfect-sales-close-plan-close-any-pitch-with-100-effective-results-on-whatsapp-eazybe-chrome-extension", destination: "/blog", permanent: true },
  { source: "/blog/productivity/top-3-chrome-extensions-that-you-must-install-right-now-to-grow-your-business", destination: "/blog", permanent: true },
  { source: "/blog/tag/crminwhatsapp/feed", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-business/how-to-get-whatsapp-green-tick-verification-in-2023-easiest-method", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/how-to-schedule-messages-on-whatsapp-with-eazybe-chrome-extension-never-miss-an-event-or-your-friends-birthday", destination: "/blog", permanent: true },
  { source: "/blog/customer-management/new-feature-whatsapp-community", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/how-whatsapp-reminder-makes-you-productive-2023-templates", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-business/whatsapp-catalogue-everything-you-need-to-know-in-2023", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-otp-how-do-you-send-an-otp-on-whatsapp", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/get-unlimited-data-on-whatsapp-with-this-trick-for-free-forget-paying-for-google-drive-storage-plans-eazybe-chrome-extension", destination: "/blog", permanent: true },
  { source: "/blog/business/eazybe-chrome-extension-how-to-install-make-your-whatsapp-incredibly-professional-within-minutes", destination: "/blog", permanent: true },
  { source: "/blog/uncategorized/craft-attractive-messages-for-customers-on-whatsapp", destination: "/blog", permanent: true },
  { source: "/blog/customer-management/how-to-create-marketing-sales-funnel-with-eazybe-chrome-extension-from-directly-your-whatsapp-account", destination: "/blog", permanent: true },
  { source: "/blog/growth/how-to-close-your-ongoing-sales-100-with-eazybe-chrome-extension-the-best-sales-closing-tool", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/15-whatsapp-business-description-samples-templates-2023", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/step-by-step-guide-view-names-on-whatsapp-without-saving-numbers-new-update-add-contacts-create-groups-archive-chats", destination: "/blog", permanent: true },
  { source: "/blog/sales/sale-closing-plan-the-best-tool-to-close-almost-all-your-deals", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/send-message-to-anyone-without-saving-their-number-on-whatsapp-from-your-mobile-or-pc", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/how-to-integrate-hubspot-with-whatsapp-for-free-easiest-method", destination: "/blog", permanent: true },
  { source: "/blog/tag/privacy-extension-for-whatsapp", destination: "/blog", permanent: true },
  { source: "/blog/login", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-2", destination: "/blog", permanent: true },
  { source: "/blog/tag/hubspot-whatsapp-integration-tutorial", destination: "/blog", permanent: true },
  { source: "/blog/growth/how-can-eazybe-help-you-increase-your-covid-era-remote-working-productivity", destination: "/blog", permanent: true },
  { source: "/blog/tag/boost-productivity-with-whatsapp-hubspot-sync", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsapp-automation", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsapp-web/page/3", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/schedule-messages-on-whatsapp-with-eazybe-chrome-extension-a-complete-guide-to-setting-reminders-and-boosting-productivity", destination: "/blog", permanent: true },
  { source: "/post/how-to-close-your-ongoing-sales-100-with-eazybe-chrome-extension-the-best-sales-closing-tool", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-broadcast-message-everything-you-need-to-know", destination: "/blog", permanent: true },
  { source: "/blog/tag/how-to-download-whatsapp-business-api", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-companion-mode-how-to-use-whatsapp-on-two-phones-with-same-number", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/message-broadcasts-in-whatsapp-everything-you-need-to-know", destination: "/blog", permanent: true },
  { source: "/blog/productivity/how-whatapp-will-take-over-email-by-2030-change-is-coming", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-business/whatsapp-business-api-everything-you-need-to-see-may-2023", destination: "/blog", permanent: true },
  { source: "/blog/tag/crmsolutions", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/how-to-add-whatsapp-on-your-wordpress-website-free-plugins", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/how-to-save-a-contact-to-phone-using-eazybe-extension", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/5-wa-web-plus-alternatives-best-whatsapp-chrome-extensions", destination: "/blog", permanent: true },
  { source: "/blog/tag/extension", destination: "/blog", permanent: true },
  { source: "/%205-wa-web-plus-alternatives-best-whatsapp-chrome-extensions", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-business/business-whatsapp-automation-free-tools-use-cases", destination: "/blog", permanent: true },
  { source: "/blog/tag/what-is-the-use-of-google-sheets", destination: "/google-sheets-whatsapp-integration", permanent: true },
  { source: "/blog/tag/eazybe-download", destination: "/blog", permanent: true },
  { source: "/extension", destination: "/", permanent: true },
  { source: "/blog/tag/chrome-extension", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/whatsapp-business/whatsapp-chatbot-for-business-how-to-get-it-for-free-in-2023", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-hacks/whatsapp-latest-update-now-send-files-upto-2gb-to-anyone-eazybe-chrome-extension", destination: "/blog", permanent: true },
  { source: "/blog/tag/web-whatsapp-com", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsapp-2023", destination: "/blog", permanent: true },
  { source: "/faq", destination: "/", permanent: true },
  { source: "/blog/aplicativo-whatsapp/modo-complementar-do-whatsapp-como-usar-o-whatsapp-em-dois-telefones-com-o-mesmo-numero", destination: "/blog", permanent: true },
  { source: "/blog/tag/gb-whatsapp-download", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsappweb", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsapp-business-descriptions-2023", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-empresarial/9-maneiras-de-usar-o-whatsapp-para-atendimento-ao-cliente-2023", destination: "/blog", permanent: true },
  { source: "/blog/negocio-de-whatsapp/__trashed", destination: "/blog", permanent: true },
  { source: "/about-cs", destination: "/", permanent: true },
  { source: "/blog/tag/brazil", destination: "/blog", permanent: true },
  { source: "/blog/tag/hubspot", destination: "/blog", permanent: true },
  { source: "/login", destination: "/", permanent: true },
  { source: "/blog/whatsapp/whatsapp", destination: "/blog", permanent: true },
  { source: "/blog/tag/chatlabelswhatsapp", destination: "/blog", permanent: true },
  { source: "/blog/category/introduction", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsapp-on-web", destination: "/blog", permanent: true },
  { source: "/blog/tag/small-business/page/3", destination: "/blog", permanent: true },
  { source: "/blog/tag/utility-chrome-extension", destination: "/blog", permanent: true },
  { source: "/coming-soon", destination: "/", permanent: true },
  { source: "/blog/category/communication-tips", destination: "/blog", permanent: true },
  { source: "/blog/tag/free-whatsapp-reminder", destination: "/blog", permanent: true },
  { source: "/blog/tag/marketing-101", destination: "/blog", permanent: true },
  { source: "/blog/category/whatsapp", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsapp-tool", destination: "/blog", permanent: true },
  { source: "/blog/tag/rocket-send", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/a-complete-guide-to-the-whatsapp-business-api-price-list-for-2023", destination: "/blog", permanent: true },
  { source: "/signup", destination: "/", permanent: true },
  { source: "/blog/tag/eazybe", destination: "/blog", permanent: true },
  { source: "/blog/tag/gb-whatsapp", destination: "/blog", permanent: true },
  { source: "/contact-pm", destination: "/", permanent: true },
  { source: "/%20synchronizing-whatsapp-conversations-with-hubspot-crm", destination: "/", permanent: true },
  { source: "/blog/tag/is-whatsapp-broadcast-good", destination: "/", permanent: true },
  { source: "/blog/tag/whatsapp-chatgpt", destination: "/", permanent: true },
  { source: "/blog/whatsapp/whatsapp-web-plus-alternatives-best-whatsapp-chrome", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsapp-business-account-login", destination: "/blog", permanent: true },
  { source: "/blog/es/negocio-de-whatsapp/5-alternativas-de-wa-web-plus-las-mejores-extensiones-de-whatsapp-para-chrome", destination: "/blog", permanent: true },
  { source: "/blog/uncategorized-pt/o-guia-completo-de-precos-da-api-de-negocios-do-whatsapp-2023", destination: "/blog", permanent: true },
  { source: "/blog-es/catalogo-de-whatsapp-todo-lo-que-necesitas-saber-en-2023", destination: "/blog", permanent: true },
  { source: "/blog/tag/1-1-1-1", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsappupdate", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-empresarial/o-que-sao-comunidades-no-whatsapp-maneiras-interessantes-de-usa-las", destination: "/blog", permanent: true },
  { source: "/blog/negocio-de-whatsapp/whatsapp-chatbot-para-empresas-como-obtenerlo-gratis-en-2023", destination: "/blog", permanent: true },
  { source: "/blog/negocio-de-whatsapp/5-alternativas-de-wa-web-plus-las-mejores-extensiones-de-whatsapp-para-chrome", destination: "/blog", permanent: true },
  { source: "/blog/tag/wordpress-plugins/feed", destination: "/blog", permanent: true },
  { source: "/blog/negocio-de-whatsapp/como-agregar-whatsapp-en-su-sitio-web-de-wordpress-complementos-gratuitos", destination: "/blog", permanent: true },
  { source: "/blog/es/tag/servicio-de-atencion-al-cliente-de-whatsapp", destination: "/es/blog", permanent: true },
  { source: "/blog/tag/whatsapp-text-tricks-tips/feed", destination: "/blog", permanent: true },
  { source: "/blog/tag/how-to-take-screenshot-of-whatsapp-status", destination: "/blog", permanent: true },
  { source: "/faq-details/gallery-slider", destination: "/", permanent: true },
  { source: "/blog/tag/green-tick-on-whatsapp/feed", destination: "/blog", permanent: true },
  { source: "/blog/tag/chatbot-on-whatsapp", destination: "/blog", permanent: true },
  { source: "/blog/tag/what-is-whatsapp-business-api/feed", destination: "/blog", permanent: true },
  { source: "/home-pt", destination: "/br", permanent: true },
  { source: "/pricinges", destination: "/", permanent: true },
  { source: "/blog/tag/streamline-communication-with-whatsapp-and-hubspot", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-empresarial/integracao-do-whatsapp-com-o-hubspot-e-processo-de-configura", destination: "/blog", permanent: true },
  { source: "/blog/aplicativo-whatsapp/como-adicionar-o-whatsapp-ao-seu-site-wordpress-plugins-gratuitos", destination: "/blog", permanent: true },
  { source: "/blog/pt/aplicativo-whatsapp/5-alternativas-wa-web-plus-as-melhores-extensoes-do-chrome-para-whatsapp", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp-empresarial/integracao-do-whatsapp-hubspot-como-sincronizar-conversas-do-whatsapp-com-o-hubspot", destination: "/blog", permanent: true },
  { source: "/blog/negocio-de-whatsapp/que-son-las-comunidades-en-whatsapp-formas-interesantes-de-usarlas", destination: "/blog", permanent: true },
  { source: "/blog/negocio-de-whatsapp/modo-complementario-de-whatsapp-como-usar-whatsapp-en-dos-telefonos-con-el-mismo-numero", destination: "/blog", permanent: true },
  { source: "/blog/negocio-de-whatsapp/9-formas-de-usar-whatsapp-para-atencion-al-cliente-2023", destination: "/blog", permanent: true },
  { source: "/blog/negocio-de-whatsapp/como-el-recordatorio-de-whatsapp-lo-hace-productivo-plantillas-2023", destination: "/blog", permanent: true },
  { source: "/blog/aplicativo-whatsapp/alternatives-do-whatsapp-mais-5-para-2023", destination: "/blog", permanent: true },
  { source: "/blog/pt/aplicativo-whatsapp/como-o-lembrete-do-whatsapp-torna-voce-produtivo-modelos-2023", destination: "/blog", permanent: true },
  { source: "/post/whatsapp-web-whatsapp-business-api", destination: "/blog", permanent: true },
  { source: "/blog/negocio-de-whatsapp/que-es-catalogue-en-whatsapp-business-como-hacerlo-y-mantenerlo", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/catalogo-do-whatsapp-tudo-o-que-voce-precisa-saber-em-2023", destination: "/blog", permanent: true },
  { source: "/blog/tag/wawebplusalternatives", destination: "/blog", permanent: true },
  { source: "/blog/author/mukund-sharma/feed/whatsapp.com", destination: "/blog", permanent: true },
  { source: "/blog/negocio-de-whatsapp/mensaje-de-difusion-de-whatsapp-todo-lo-que-necesita-saber", destination: "/blog", permanent: true },
  { source: "/blog/aplicativo-whatsapp/o-que-e-catalogo-no-whatsapp-buisness-e-como-mante-lo", destination: "/blog", permanent: true },
  { source: "/blog/whatsapp/como-o-lembrete-do-whatsapp-torna-voce-produtivo-modelos-2023", destination: "/blog", permanent: true },
  { source: "/blog/tag/whatsapp-bulk-message", destination: "/blog", permanent: true },
  { source: "/post/edit-andriod-contacts-on-whatsapp-without-leaving-the-app", destination: "/blog", permanent: true },
  { source: "/post/%20edit-andriod-contacts-on-whatsapp-without-leaving-the-app", destination: "/blog", permanent: true },
  { source: "/blog/tag/otp-whatsapp/feed", destination: "/blog", permanent: true },
  { source: "/post/whatsapp-latest-update-now-send-files-upto-2gb-to-anyone-eazybe-chrome-extension", destination: "/blog", permanent: true },
  { source: "/post/how-to-use-google-sheets-on-whatsapp-for-free-easiest-method", destination: "/google-sheets-whatsapp-integration", permanent: true },
  { source: "/home-pts", destination: "/br", permanent: true },
  { source: "/blog/tag/whatsapp-web-chrome-extension/feed", destination: "/blog", permanent: true },
  { source: "/blog/pt/tag/comunicacao-simplificada-com-a-integracao-whatsapp-e-hubspot/feed", destination: "/br/blog", permanent: true },
  { source: "/integrations-pts", destination: "/br", permanent: true },
  { source: "/pricing-pts", destination: "/br/pricing", permanent: true },
  { source: "/post/set-up-google-calendar-on-whatsapp-with-eazybe-chrome-extension", destination: "/google-calendar-whatsapp-integration", permanent: true },
  { source: "/payment-canceled", destination: "/", permanent: true },
  { source: "/blog/whatsapp/whatsapp-customer-service-software", destination: "/blog", permanent: true },
  { source: "/post/how-to-use-chatgpt-4-0-on-whatsapp", destination: "/blog", permanent: true },
  { source: "/post/whatsapp-community-everything-you-need-to-know-about-the-latest-update", destination: "/blog", permanent: true },
  { source: "/blog/productivity/schedule-messages-in-whatsapp//1000", destination: "/blog", permanent: true },
  { source: "/blog-es/5-alternativas-a-wa-web-plus-las-mejores-extensiones-de-whatsapp-chrome", destination: "/es/blog", permanent: true },
  { source: "/blog-es/%205-alternativas-a-wa-web-plus-las-mejores-extensiones-de-whatsapp-chrome", destination: "/es/blog", permanent: true },
  { source: "/post/whatsapp-companion-mode-use-whatsapp-on-two-phones-with-same-number", destination: "/blog", permanent: true },
  { source: "/subscription-canceled", destination: "/", permanent: true },
  { source: "/blog/whatsapp/9-ways-to-use-whatsapp-for-customer-service-2023", destination: "/blog", permanent: true },
  { source: "/blog/tag/chrome-extension/feed", destination: "/blog", permanent: true },
  { source: "/post/%20whatsapp-companion-mode-use-whatsapp-on-two-phones-with-same-number", destination: "/blog", permanent: true },
  { source: "/blog/es/negocio-de-whatsapp/whatsapp-chatbot-para-empresas-como-obtenerlo-gratis-en-2023", destination: "/es/blog", permanent: true },
  { source: "/post/chatgpt-4-0-on-whatsapp-latest-update-with-eazybe-chrome-extension", destination: "/blog", permanent: true },
  { source: "/post/%20chatgpt-4-0-on-whatsapp-latest-update-with-eazybe-chrome-extension", destination: "/blog", permanent: true },
  { source: "/post/manage-your-hubspot-crm-on-whatsapp-with-eazybe-experience-real-time-changes-much-more", destination: "/", permanent: true },
  { source: "/post/read-deleted-messages-on-whatsapp-easiest-methods", destination: "/blog/how-to-read-deleted-messages-on-whatsapp", permanent: true },
  { source: "/comparison/comparison-between-eazybe-and-prime-sender", destination: "/comparison", permanent: true },
  { source: "/hubspot-crm-form", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/integrate-zoho-copy", destination: "/zoho-whatsapp-integration", permanent: true },
  { source: "/enquiry-thanks", destination: "/", permanent: true },
  { source: "/hubspot-crm-form-es", destination: "/es/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/es/negocio-de-whatsapp/mensaje-de-difusion-de-whatsapp-todo-lo-que-necesita-saber", destination: "/es/blog", permanent: true },
  { source: "/go-offline-on-whatsapp-without-turning-off-the-internet-whatsapp-proxy-setting", destination: "/blog/how-to-appear-offline-on-whatsapp", permanent: true },
  { source: "/post/%20go-offline-without-turning-off-internet-how-to-turn-off-whatsapp", destination: "/blog/how-to-appear-offline-on-whatsapp", permanent: true },
  { source: "/post/go-offline-on-whatsapp-without-turning-off-the-internet-whatsapp-proxy-setting", destination: "/blog/how-to-appear-offline-on-whatsapp", permanent: true },
  { source: "/comparison/comparison-between-eazybe-and-wa-plus", destination: "/comparison", permanent: true },
  { source: "/post/go-offline-without-turning-off-internet-how-to-turn-off-whatsapp", destination: "/blog/how-to-appear-offline-on-whatsapp", permanent: true },
  { source: "/post/%20how-to-set-birthday-reminders-on-whatsapp", destination: "/blog", permanent: true },
  { source: "/post/%20read-deleted-messages-on-whatsapp-easiest-methods", destination: "/blog", permanent: true },
  { source: "/comparison/comparison-between-eazybe-and-cooby", destination: "/comparison", permanent: true },
  { source: "/post/how-to-read-deleted-messages-on-whatsapp-easiest-methods-ios-android-whatsapp-web", destination: "/blog/how-to-read-deleted-messages-on-whatsapp", permanent: true },
  { source: "/post/whatsapp-automation-for-business-free-tools-use-cases", destination: "/blog", permanent: true },
  { source: "/post/beginners-guide-mastering-whatsapp-automation-for-sales", destination: "/", permanent: true },
  { source: "/blog/whatsapp/how-to-read-deleted-messages-on-whatsapp-easiest-methods-ios-android-whatsapp-web", destination: "/blog/how-to-read-deleted-messages-on-whatsapp", permanent: true },
  { source: "/post/beginners-guide-how-to-recover-deleted-whatsapp-photos", destination: "/blog", permanent: true },
  { source: "/post/how-to-see-deleted-messages-on-whatsapp-revealed", destination: "/blog", permanent: true },
  { source: "/comparison/comparison-between-eazybe-and-wa-web-plus", destination: "/comparison", permanent: true },
  { source: "/comparison/comparison-between-eazybe-and-wa-sender", destination: "/comparison", permanent: true },
  { source: "/post/7-wa-deck-alternatives-which-one-should-you-choose", destination: "/blog", permanent: true },
  { source: "/post/boost-sales-efficiency-eazybes-hubspot-whatsapp-integration", destination: "/blog", permanent: true },
  { source: "/post/boost-your-crm-efficiency-a-comprehensive-guide-to-integrating-whatsapp-with-hubspot-using-eazybe", destination: "/blog", permanent: true },
  { source: "/post/boost-your-sales-with-zoho-crm-whatsapp-integration", destination: "/blog", permanent: true },
  { source: "/post/comparing-wa-web-plus-alternatives-which-is-right-for-you", destination: "/blog", permanent: true },
  { source: "/post/craft-attractive-messages-for-customers-on-whatsapp", destination: "/blog", permanent: true },
  { source: "/post/15-whatsapp-business-description-samples-templates-2023", destination: "/blog", permanent: true },
  { source: "/post/essential-glossary-of-artificial-intelligence-ai-terms", destination: "/blog", permanent: true },
  { source: "/post/boost-your-sales-process-with-these-15-automation-tools", destination: "/blog", permanent: true },
  { source: "/post/15-best-ai-drive-sales-tool-for-b2c-companies-using-whatsapp-business-2025", destination: "/", permanent: true },
  { source: "/post/effective-approaches-for-balancing-customer-retention-acquisition", destination: "/", permanent: true },
  { source: "/post/15-best-ai-driven-sales-tools-for-b2c-companies", destination: "/", permanent: true },
  { source: "/post/whatsapp-vs-whatsapp-business-vs-whatsapp-api", destination: "/", permanent: true },
  { source: "/post/create-whatsapp-channel-boost-communication-strategy", destination: "/", permanent: true },
  { source: "/post/get-started-with-chatgpt-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/beginners-guide-mastering-whatsapp-crm-for-beginners", destination: "/", permanent: true },
  { source: "/post/schedule-message-whatsapp-unlocking-the-power-of-automation", destination: "/", permanent: true },
  { source: "/post/%20get-started-with-chatgpt-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/10-ways-whatsapp-crm-can-revolutionize-your-business", destination: "/", permanent: true },
  { source: "/post/access-chatgpt-on-whatsapp-with-this-top-3-whatsapp-chrome-extensions", destination: "/", permanent: true },
  { source: "/post/discover-10-whatsapp-hacks-for-2025-you-need-now", destination: "/", permanent: true },
  { source: "/post/chatgpt-4-0-on-whatsapp-eazybe-extension-for-ai-sales", destination: "/", permanent: true },
  { source: "/post/connect-better-the-easy-way-to-whatsapp-web-login", destination: "/", permanent: true },
  { source: "/post/whatsapp-business-vs-whatsapp-vs-whatsapp-api", destination: "/", permanent: true },
  { source: "/post/what-is-whatsapp-coexistence-and-how-it-will-transform-b2c-sales-an-eazybe-leadership-perspective", destination: "/", permanent: true },
  { source: "/post/5-reasons-why-marketing-is-more-important-than-ever-in-2023", destination: "/", permanent: true },
  { source: "/post/10-whatsapp-crm-hacks-for-explosive-sales-results", destination: "/", permanent: true },
  { source: "/post/all-you-need-to-know-about-zoho-crm", destination: "/", permanent: true },
  { source: "/post/9-ways-to-use-whatsapp-for-customer-service-2023", destination: "/", permanent: true },
  { source: "/post/chatgpt-4-0-on-whatsapp-install-eazybe-send-ai-whatsapp-messages", destination: "/", permanent: true },
  { source: "/post/boost-your-workflow-with-webhooks-integration-with-whatsapp", destination: "/", permanent: true },
  { source: "/post/5-wa-web-plus-alternatives-best-whatsapp-chrome-extensions", destination: "/", permanent: true },
  { source: "/post/guide-to-building-an-effective-b2b-sales-strategy", destination: "/", permanent: true },
  { source: "/post/mastering-b2b-sales-prospecting-a-beginners-guide", destination: "/", permanent: true },
  { source: "/post/discover-the-best-whatsapp-business-api-alternatives", destination: "/", permanent: true },
  { source: "/post/the-sales-agents-ultimate-guide-to-whatsapp-coexistence-close-more-deals-without-changing-apps", destination: "/", permanent: true },
  { source: "/post/b2b-account-management-using-whatsapp-groups-and-eazybe-integrationv", destination: "/", permanent: true },
  { source: "/post/customer-retention-loyalty-key-differences-explained", destination: "/", permanent: true },
  { source: "/post/exploring-zoho-crm-cost-plans-features-and-add-ons", destination: "/", permanent: true },
  { source: "/post/exploring-the-best-alternatives-to-whatsup-plus", destination: "/", permanent: true },
  { source: "/post/integrate-hubspot-with-whatsapp-easiest-method", destination: "/", permanent: true },
  { source: "/post/whatsapp-marketing-with-100-accurate-results-skyrocket-your-sales-with-eazybe", destination: "/", permanent: true },
  { source: "/post/save-a-contact-to-phone-using-eazybe-extension", destination: "/", permanent: true },
  { source: "/post/how-to-use-chatgpt-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/get-organized-with-hubspot-free-crm-start-now", destination: "/", permanent: true },
  { source: "/post/apply-for-green-tick-on-whatsapp-business", destination: "/", permanent: true },
  { source: "/post/google-calendar-on-whatsapp-eazybe-extension-guide", destination: "/", permanent: true },
  { source: "/post/how-to-set-birthday-reminders-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/hubspot-whatsapp-integration-guide-seamless-connection", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/post/how-ai-crm-whatsapp-can-revolutionize-your-business-in-2025", destination: "/", permanent: true },
  { source: "/post/add-whatsapp-on-your-wordpress-website", destination: "/", permanent: true },
  { source: "/post/create-marketing-sales-funnel-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/how-to-read-deleted-messages-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/how-hubspot-hit-100m--and-how-you-can-too", destination: "/", permanent: true },
  { source: "/post/eazybe-help-you-increase-your-covid-era-remote-working-productivity", destination: "/", permanent: true },
  { source: "/post/unlimited-data-on-whatsapp-with-this-trick-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/elevate-results-whatsapp-integration-for-crm-success", destination: "/", permanent: true },
  { source: "/post/elevate-sales-team-performance-with-crm-whatsapp-integration", destination: "/", permanent: true },
  { source: "/post/eazybe-chrome-extension-install-make-your-whatsapp-incredibly-professional", destination: "/", permanent: true },
  { source: "/post/do-you-use-whatsapp-effectively-for-sales", destination: "/", permanent: true },
  { source: "/post/eazybes-bitrix24-integration-transforming-customer-management", destination: "/", permanent: true },
  { source: "/post/ditch-wa-deck-top-7-alternatives-for-better-whatsapp-experience", destination: "/", permanent: true },
  { source: "/post/how-to-appear-offline-on-whatsapp", destination: "/how-to-appear-offline-on-whatsapp", permanent: true },
  { source: "/post/how-to-edit-andriod-contacts-on-whatsapp-without-leaving-the-app", destination: "/", permanent: true },
  { source: "/post/get-whatsapp-green-tick-verification-easiest-method", destination: "/", permanent: true },
  { source: "/post/do-team-management-on-whatsapp-use-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/how-small-businesses-can-grow-in-2022", destination: "/", permanent: true },
  { source: "/post/set-reminders-on-whatsapp-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/leadsquared-crm-the-ultimate-sales-marketing-solution", destination: "/", permanent: true },
  { source: "/post/revolutionizing-crm-through-whatsapp-zoho-integration-free-using-eazybe", destination: "/", permanent: true },
  { source: "/post/send-message-without-saving-their-number-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/make-your-texts-stand-out-with-these-whatsapp-message-tricks", destination: "/", permanent: true },
  { source: "/post/whatsapp-business-groups-and-broadcast-lists-to-reach-your-customers", destination: "/", permanent: true },
  { source: "/post/organize-chats-on-whatsapp-whatsapp-look-clean-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/send-bulk-messages-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/hubspot-crm-cost-what-you-need-to-know", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/post/how-to-easily-restore-deleted-whatsapp-images-and-videos-revealed", destination: "/", permanent: true },
  { source: "/post/hubspot-as-a-crm-the-key-to-a-streamlined-sales-process", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/post/manage-your-hubspot-crm-on-whatsapp-with-eazybe", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/post/how-whatapp-will-take-over-email-by-2030", destination: "/", permanent: true },
  { source: "/post/create-a-chat-gpt-3-ai-chatbot-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/travel-agency-crm-benefits-whatsapp-hubspot-integration", destination: "/", permanent: true },
  { source: "/post/implementing-whatsapp-quick-replies-for-your-team", destination: "/", permanent: true },
  { source: "/post/personalized-marketing-with-whatsapp", destination: "/", permanent: true },
  { source: "/post/sales-are-now-switching-to-messages", destination: "/", permanent: true },
  { source: "/post/how-to-easily-transfer-whatsapp-chats-from-android-to-iphone", destination: "/", permanent: true },
  { source: "/post/boost-sales-with-hubspot-whatsapp-integration", destination: "/", permanent: true },
  { source: "/post/boost-loyalty-improve-customer-retention-strategies", destination: "/", permanent: true },
  { source: "/post/how-to-set-up-and-integrate-whatsapp-webhook-2-methods", destination: "/", permanent: true },
  { source: "/post/difference-between-whatsapp-web-whatsapp-business-api", destination: "/", permanent: true },
  { source: "/post/expert-tips-for-successful-sales-recruitment", destination: "/", permanent: true },
  { source: "/post/install-chrome-extension-in-microsoft-edge-use-this-hack", destination: "/", permanent: true },
  { source: "/post/navigating-top-challenges-crm-users-will-face-in-2025", destination: "/", permanent: true },
  { source: "/post/how-to-send-bulk-messages-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/hubspot-crm-whatsapp-integration", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/post/how-whatsapp-reminder-makes-you-productive", destination: "/", permanent: true },
  { source: "/post/manage-google-calendar-through-eazybe-whatsapp-chrome-extensions", destination: "/", permanent: true },
  { source: "/post/close-your-ongoing-sales-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/best-tool-to-close-almost-all-your-deals", destination: "/", permanent: true },
  { source: "/post/whatsapp-polls-their-benefits-and-best-practices", destination: "/", permanent: true },
  { source: "/post/use-google-sheets-on-whatsapp", destination: "/google-sheets-whatsapp-integration", permanent: true },
  { source: "/post/sales-closing-phrases-to-avoid", destination: "/", permanent: true },
  { source: "/post/unlocking-the-benefits-of-crm-systems-for-your-business", destination: "/", permanent: true },
  { source: "/post/quick-steps-to-unblock-your-whatsapp-business-account", destination: "/", permanent: true },
  { source: "/post/synchronizing-whatsapp-conversations-with-hubspot-crm", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/post/schedule-messages-on-whatsapp-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/7-alternatives-of-wa-plus", destination: "/", permanent: true },
  { source: "/post/whatsapp-update-now-send-files-upto-2gb-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/the-perfect-sales-close-plan-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/ultimate-guide-to-whatsapp-team-inbox-backup", destination: "/", permanent: true },
  { source: "/post/whatsapp-companion-mode-how-to-use-whatsapp-on-two-phones", destination: "/", permanent: true },
  { source: "/post/whatsapp-broadcast-message-everything-you-need-to-know", destination: "/", permanent: true },
  { source: "/post/unlocking-hubspot-whatsapp-integration-free-tips", destination: "/", permanent: true },
  { source: "/post/whatsapp-business-api-everything-you-need-to-see", destination: "/", permanent: true },
  { source: "/post/7-best-alternative-of-cooby-elevate-your-experience", destination: "/", permanent: true },
  { source: "/post/whatsapp-business-description-samples", destination: "/", permanent: true },
  { source: "/post/what-is-customer-retention-strategies-and-metrics", destination: "/", permanent: true },
  { source: "/post/whatsapp-hubspot-integration-how-to-sync-whatsapp-chats-with-hubspot", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/post/the-complete-guide-to-pricing-for-whatsapp-business-api-2023", destination: "/", permanent: true },
  { source: "/post/unlocking-the-power-of-whatsapp-ads-tips-for-successful-campaigns", destination: "/", permanent: true },
  { source: "/post/whatsapp-catalogue-everything-you-need-to-know-in-2023", destination: "/", permanent: true },
  { source: "/post/whatsapp-community-know-everything-about-the-latest-update", destination: "/", permanent: true },
  { source: "/post/streamlining-customer-communication-integrating-whatsapp-with-hubspot", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/post/the-future-of-crm-top-integration-tools-transforming-customer-relationship-management-in-2024", destination: "/", permanent: true },
  { source: "/post/unlock-productivity-with-tasks-hubspot-whatsapp-integration", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/post/use-these-7-proven-strategies-to-grow-your-business", destination: "/", permanent: true },
  { source: "/post/whatsapp-automation", destination: "/blog/whatsapp-automation", permanent: true },
  { source: "/post/streamlining-crm-with-whatsapp-web-integration", destination: "/", permanent: true },
  { source: "/post/whatsapp-otp-how-do-you-send-an-otp-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/customer-support-freshdesk-and-whatsapp-integration-eazybe", destination: "/freshdesk-whatsapp-integration", permanent: true },
  { source: "/post/schedule-messages-in-whatsapp", destination: "/", permanent: true },
  { source: "/post/the-ultimate-alternative-to-cooby-kiosk-unipile-and-more", destination: "/", permanent: true },
  { source: "/post/top-whatsapp-alternatives-2024-find-your-perfect-match", destination: "/", permanent: true },
  { source: "/post/unveiling-the-preference-for-whatsapp-over-sms-emails", destination: "/", permanent: true },
  { source: "/post/7-alternatives-of-wa-sender", destination: "/", permanent: true },
  { source: "/post/whatsapp-otp-how-to-send-otp-with-whatsapp-in-2023", destination: "/", permanent: true },
  { source: "/post/the-perfect-match-whatsapp-meets-hubspot-for-seamless-crm", destination: "/", permanent: true },
  { source: "/post/whatsapp-chatbot-for-business-how-to-get-it-for-free-in-2023", destination: "/", permanent: true },
  { source: "/post/top-3-chrome-extensions-that-you-must-install-right-now", destination: "/", permanent: true },
  { source: "/post/business-guide-build-sales-team-high-performance", destination: "/", permanent: true },
  { source: "/post/the-ultimate-crm-buying-guide-how-to-choose-the-right-crm-for-your-sales-team-in-2025", destination: "/", permanent: true },
  { source: "/post/whatsapp-coexistence", destination: "/", permanent: true },
  { source: "/post/communities-in-whatsapp-interesting-ways-to-use-them", destination: "/", permanent: true },
  { source: "/post/whatsapp-hacks-how-to-message-without-saving-contact", destination: "/", permanent: true },
  { source: "/post/the-power-of-ai-in-sales-introducing-eazybes-revolutionary-ai-assistant-for-2024", destination: "/", permanent: true },
  { source: "/post/catalog-in-whatsapp-business-how-to-make-and-maintain-it", destination: "/", permanent: true },
  { source: "/post/step-by-step-guide-view-names-on-whatsapp-without-saving-numbers", destination: "/", permanent: true },
  { source: "/post/start-chat-without-saving-the-number-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/test-blog", destination: "/", permanent: true },
  { source: "/post/will-ai-replace-sales-agents-heres-what-the-latest-data-and-trends-reveal", destination: "/", permanent: true },
  { source: "/post/zoho-crm-free-your-ultimate-crm-solution", destination: "/zoho-whatsapp-integration", permanent: true },
  { source: "/post/whatsapp-verification-call-stopped-the-impact-solutions-and-account-security", destination: "/", permanent: true },
  { source: "/pt", destination: "/br", permanent: true },
  { source: "/post/%20eazybe-chrome-extension-install-make-your-whatsapp-incredibly-professional", destination: "/", permanent: true },
  { source: "/post/%2015-whatsapp-business-description-samples-templates-2023", destination: "/", permanent: true },
  { source: "/blog/access-chatgpt-on-whatsapp-with-this-top-3-whatsapp-chrome-extensions", destination: "/", permanent: true },
  { source: "/post/%20how-to-use-chatgpt-4-0-on-whatsapp", destination: "/", permanent: true },
  { source: "/privacy-pt", destination: "/br/privacy", permanent: true },
  { source: "/privacy-es", destination: "/es/privacy", permanent: true },
  { source: "/hubspot-es", destination: "/es/hubspot-whatsapp-integration", permanent: true },
  { source: "/comparacao-pt", destination: "/br", permanent: true },
  { source: "/comparacion-es", destination: "/es", permanent: true },
  { source: "/integrations-pt", destination: "/br", permanent: true },
  { source: "/terms-of-service-es", destination: "/es/terms", permanent: true },
  { source: "/terms-of-service-pt", destination: "/br/terms", permanent: true },
  { source: "/salesforce-es", destination: "/es/salesforce-whatsapp-integration", permanent: true },
  { source: "/hubspot-pt", destination: "/br/salesforce-whatsapp-integration", permanent: true },
  { source: "/blog/schedule-messages-in-whatsapp", destination: "/", permanent: true },
  { source: "/blog/schedule-message-whatsapp-unlocking-the-power-of-automation", destination: "/", permanent: true },
  { source: "/blog/schedule-messages-on-whatsapp-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/blog/how-whatsapp-reminder-makes-you-productive", destination: "/", permanent: true },
  { source: "/blog/15-whatsapp-business-description-samples-templates-2023", destination: "/blog/15-whatsapp-business-description-samples-templates", permanent: true },
  { source: "/pricing-es", destination: "/es/pricing", permanent: true },
  { source: "/blog/ultimate-guide-to-whatsapp-team-inbox-backup", destination: "/", permanent: true },
  { source: "/blog-es/conectese-mejor-la-forma-mas-sencilla-de-iniciar-sesion-en-whatsapp-web", destination: "/es", permanent: true },
  { source: "/blog/5-wa-web-plus-alternatives-best-whatsapp-chrome-extensions", destination: "/es", permanent: true },
  { source: "/blog-es/5-alternativas-a-wa-web-plus", destination: "/es", permanent: true },
  { source: "/post/%20synchronizing-whatsapp-conversations-with-hubspot-crm", destination: "/", permanent: true },
  { source: "/blog-es/%205-alternativas-a-wa-web-plus", destination: "/es", permanent: true },
  { source: "/post/%20send-bulk-messages-on-whatsapp", destination: "/", permanent: true },
  { source: "/blog/%20send-bulk-messages-on-whatsapp", destination: "/", permanent: true },
  { source: "/blog/whatsapp-broadcast-message-everything-you-need-to-know", destination: "/", permanent: true },
  { source: "/blog/whatsapp-business-groups-and-broadcast-lists-to-reach-your-customers", destination: "/", permanent: true },
  { source: "/blog-es/como-ver-mensajes-eliminados-en-whatsapp-revelado", destination: "/es/blog", permanent: true },
  { source: "/blog/top-5-wa-web-plus-alternatives", destination: "/", permanent: true },
  { source: "/blog-pt/comparando-7-alternativas-do-wa-web-plus-qual-e-a-certa-para-voce", destination: "/br/blog", permanent: true },
  { source: "/blog-es/comparacion-de-7-alternativas-de-wa-web-plus-cual-es-la-adecuada-para-usted", destination: "/es/blog", permanent: true },
  { source: "/pricing-pt", destination: "/br/pricing", permanent: true },
  { source: "/all-crm-form-pt", destination: "/", permanent: true },
  { source: "/blog/set-reminders-on-whatsapp-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/blog-pt/o-guia-completo-de-precos-da-api-whatsapp-business", destination: "/br/blog", permanent: true },
  { source: "/create-a-chat-gpt-3-ai-chatbot-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/ send-bulk-messages-on-whatsapp", destination: "/whatsapp-api/broadcast", permanent: true },
  { source: "/post/ how-to-use-chatgpt-4-0-on-whatsapp", destination: "/", permanent: true },
  { source: "/zoho-crm-form", destination: "/zoho-whatsapp-integration", permanent: true },
  { source: "/5-wa-web-plus-alternatives-best-whatsapp-chrome-extensions", destination: "/", permanent: true },
  { source: "/post/ chatgpt-4-0-on-whatsapp-install-eazybe-send-ai-whatsapp-messages", destination: "/", permanent: true },
  { source: "/post/ how-to-set-birthday-reminders-on-whatsapp", destination: "/", permanent: true },
  { source: "/catalog-in-whatsapp-business-how-to-make-and-maintain-it", destination: "/", permanent: true },
  { source: "/top-5-whatsapp-alternatives-for-2023", destination: "/", permanent: true },
  { source: "/enquiry", destination: "/", permanent: true },
  { source: "/apply-for-green-tick-on-whatsapp-business", destination: "/", permanent: true },
  { source: "/whatsapp-business-groups-and-broadcast-lists-to-reach-your-customers", destination: "/", permanent: true },
  { source: "/post/ chatgpt-4-0-on-whatsapp-latest-update-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/whatsapp-web-whatsapp-business-api", destination: "/", permanent: true },
  { source: "/post/ access-chatgpt-on-whatsapp-with-this-top-3-whatsapp-chrome-extensions", destination: "/", permanent: true },
  { source: "/the-complete-guide-to-pricing-for-whatsapp-business-api-2023", destination: "/", permanent: true },
  { source: "/communities-in-whatsapp-interesting-ways-to-use-them", destination: "/", permanent: true },
  { source: "/post/ whatsapp-companion-mode-use-whatsapp-on-two-phones-with-same-number", destination: "/", permanent: true },
  { source: "/post/ set-up-google-calendar-on-whatsapp-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/ manage-google-calendar-through-eazybe-whatsapp-chrome-extensions", destination: "/", permanent: true },
  { source: "/post/ whatsapp-marketing-with-100-accurate-results-skyrocket-your-sales-with-eazybe", destination: "/", permanent: true },
  { source: "/post/ add-whatsapp-on-your-wordpress-website", destination: "/", permanent: true },
  { source: "/post/ best-tool-to-close-almost-all-your-deals", destination: "/", permanent: true },
  { source: "/post/ 5-wa-web-plus-alternatives-best-whatsapp-chrome-extensions", destination: "/", permanent: true },
  { source: "/post/ set-reminders-on-whatsapp-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/ edit-andriod-contacts-on-whatsapp-without-leaving-the-app", destination: "/", permanent: true },
  { source: "/post/ the-complete-guide-to-pricing-for-whatsapp-business-api-2023", destination: "/", permanent: true },
  { source: "/post/ synchronizing-whatsapp-conversations-with-hubspot-crm", destination: "/", permanent: true },
  { source: "/post/ how-whatapp-will-take-over-email-by-2030", destination: "/", permanent: true },
  { source: "/post/ get-whatsapp-green-tick-verification-easiest-method", destination: "/", permanent: true },
  { source: "/post/ catalog-in-whatsapp-business-how-to-make-and-maintain-it", destination: "/", permanent: true },
  { source: "/post/ whatsapp-broadcast-message-everything-you-need-to-know", destination: "/whatsapp-api/broadcast", permanent: true },
  { source: "/post/ communities-in-whatsapp-interesting-ways-to-use-them", destination: "/", permanent: true },
  { source: "/post/ whatsapp-hubspot-integration-how-to-sync-whatsapp-chats-with-hubspot", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/post/ how-small-businesses-can-grow-in-2022", destination: "/", permanent: true },
  { source: "/post/ use-google-sheets-on-whatsapp", destination: "/google-sheets-whatsapp-integration", permanent: true },
  { source: "/terms-of-service", destination: "/", permanent: true },
  { source: "/post/ install-chrome-extension-in-microsoft-edge-use-this-hack", destination: "/", permanent: true },
  { source: "/post/ whatsapp-business-groups-and-broadcast-lists-to-reach-your-customers", destination: "/whatsapp-api/broadcast", permanent: true },
  { source: "/post/ schedule-messages-on-whatsapp-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/ personalized-marketing-with-whatsapp", destination: "/", permanent: true },
  { source: "/post/ make-your-texts-stand-out-with-these-whatsapp-message-tricks", destination: "/", permanent: true },
  { source: "/post/ apply-for-green-tick-on-whatsapp-business", destination: "/", permanent: true },
  { source: "/post/ use-these-7-proven-strategies-to-grow-your-business", destination: "/", permanent: true },
  { source: "/post/ sales-are-now-switching-to-messages", destination: "/", permanent: true },
  { source: "/post/ do-team-management-on-whatsapp-use-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/ whatsapp-web-whatsapp-business-api", destination: "/", permanent: true },
  { source: "/post/ organize-chats-on-whatsapp-whatsapp-look-clean-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/ manage-your-hubspot-crm-on-whatsapp-with-eazybe", destination: "/", permanent: true },
  { source: "/post/ create-a-chat-gpt-3-ai-chatbot-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/ 5-reasons-why-marketing-is-more-important-than-ever-in-2023", destination: "/", permanent: true },
  { source: "/post/ the-perfect-sales-close-plan-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/ top-3-chrome-extensions-that-you-must-install-right-now", destination: "/", permanent: true },
  { source: "/post/ whatsapp-community-know-everything-about-the-latest-update", destination: "/", permanent: true },
  { source: "/post/ how-whatsapp-reminder-makes-you-productive", destination: "/", permanent: true },
  { source: "/post/ whatsapp-catalogue-everything-you-need-to-know-in-2023", destination: "/", permanent: true },
  { source: "/post/ whatsapp-otp-how-do-you-send-an-otp-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/ unlimited-data-on-whatsapp-with-this-trick-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/ eazybe-chrome-extension-install-make-your-whatsapp-incredibly-professional", destination: "/", permanent: true },
  { source: "/post/ craft-attractive-messages-for-customers-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/ create-marketing-sales-funnel-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/ close-your-ongoing-sales-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/post/ 15-whatsapp-business-description-samples-templates-2023", destination: "/", permanent: true },
  { source: "/post/ step-by-step-guide-view-names-on-whatsapp-without-saving-numbers", destination: "/", permanent: true },
  { source: "/post/ send-message-without-saving-their-number-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/ integrate-hubspot-with-whatsapp-easiest-method", destination: "/", permanent: true },
  { source: "/post/ streamlining-customer-communication-integrating-whatsapp-with-hubspot", destination: "/", permanent: true },
  { source: "/post/ eazybe-help-you-increase-your-covid-era-remote-working-productivity", destination: "/", permanent: true },
  { source: "/post/ whatsapp-business-api-everything-you-need-to-see", destination: "/", permanent: true },
  { source: "/post/ save-a-contact-to-phone-using-eazybe-extension", destination: "/", permanent: true },
  { source: "/ 5-wa-web-plus-alternatives-best-whatsapp-chrome-extensions", destination: "/", permanent: true },
  { source: "/post/ whatsapp-automation-for-business-free-tools-use-cases", destination: "/", permanent: true },
  { source: "/post/ whatsapp-chatbot-for-business-how-to-get-it-for-free-in-2023", destination: "/", permanent: true },
  { source: "/post/ whatsapp-update-now-send-files-upto-2gb-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/blog-pt/ modo-complementar-do-whatsapp-como-usar-o-whatsapp-em-dois-telefones-com-o-mesmo-numero", destination: "/", permanent: true },
  { source: "/blog-pt/ 9-maneiras-de-usar-o-whatsapp-para-atendimento-ao-cliente", destination: "/", permanent: true },
  { source: "/blog-es/ 5-alternativas-a-wa-web-plus-las-mejores-extensiones-de-whatsapp-chrome", destination: "/", permanent: true },
  { source: "/blog-pt/ o-guia-completo-de-precos-da-api-whatsapp-business", destination: "/", permanent: true },
  { source: "/blog-es/ catalogo-de-whatsapp-todo-lo-que-necesitas-saber-en-2023-2024", destination: "/", permanent: true },
  { source: "/blog-pt/ comunidade-whatsapp-tudo-o-que-voce-precisa-saber-sobre-a-ultima-atualizacao", destination: "/", permanent: true },
  { source: "/blog-es/ chatbot-de-whatsapp-para-empresas-como-conseguirlo-gratis-en-2023", destination: "/", permanent: true },
  { source: "/blog-es/ como-agregar-whatsapp-en-su-sitio-web-de-wordpress-complementos-gratuitos", destination: "/es", permanent: true },
  { source: "/blog-es/ como-el-recordatorio-de-whatsapp-te-hace-productiva", destination: "/es", permanent: true },
  { source: "/post/ difference-between-whatsapp-web-whatsapp-business-api", destination: "/", permanent: true },
  { source: "/blog-pt/ integracao-do-whatsapp-hubspot-como-sincronizar-bate-papos-do-whatsapp-com-o-hubspot", destination: "/br", permanent: true },
  { source: "/blog-pt/ como-adicionar-o-whatsapp-ao-seu-site-wordpress", destination: "/br", permanent: true },
  { source: "/blog-pt/ 5-alternativas-wa-web-plus-melhores-extensoes-do-whatsapp-para-chrome", destination: "/br", permanent: true },
  { source: "/blog-pt/ como-sincronizar-conversas-do-whatsapp-com-hubspot-crm", destination: "/br", permanent: true },
  { source: "/blog-es/ que-son-las-comunidades-en-whatsapp-formas-interesantes-de-utilizarlos", destination: "/es", permanent: true },
  { source: "/blog-es/ modo-complementario-de-whatsapp-como-usar-whatsapp-en-dos-telefonos-con-el-mismo-numero", destination: "/es", permanent: true },
  { source: "/blog-es/ 9-formas-de-utilizar-whatsapp-para-atencion-al-cliente-2023", destination: "/es", permanent: true },
  { source: "/blog-pt/ como-o-lembrete-do-whatsapp-torna-voce-produtivo", destination: "/br", permanent: true },
  { source: "/blog-pt/ o-que-e-catalogo-no-whatsapp-business-como-fazer-e-manter", destination: "/br", permanent: true },
  { source: "/blog-es/ mensaje-de-difusion-de-whatsapp-todo-lo-que-necesitas-saber", destination: "/es", permanent: true },
  { source: "/blog-pt/ catalogo-do-whatsapp-tudo-o-que-voce-precisa-saber-em-2023", destination: "/br", permanent: true },
  { source: "/post/ how-to-edit-andriod-contacts-on-whatsapp-without-leaving-the-app", destination: "/", permanent: true },
  { source: "/blog-pt/zoho-crm-free-started", destination: "/br/zoho-whatsapp-integration", permanent: true },
  { source: "/payment-cancelled", destination: "/", permanent: true },
  { source: "/post/ google-calendar-on-whatsapp-eazybe-extension-guide", destination: "/google-calendar-whatsapp-integration", permanent: true },
  { source: "/post/ get-started-with-chatgpt-on-whatsapp", destination: "/", permanent: true },
  { source: "/post/ whatsapp-companion-mode-how-to-use-whatsapp-on-two-phones", destination: "/", permanent: true },
  { source: "/blog-es/ 5-alternativas-a-wa-web-plus", destination: "/es", permanent: true },
  { source: "/post/ chatgpt-4-0-on-whatsapp-eazybe-extension-for-ai-sales", destination: "/", permanent: true },
  { source: "/lp/hubspot-crm-form", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/lp/enquiry-thanks", destination: "/es/hubspot-whatsapp-integration", permanent: true },
  { source: "/lp/hubspot-crm-form-es", destination: "/es/hubspot-whatsapp-integration", permanent: true },
  { source: "/product/freshdesk-whatsapp-integration", destination: "/freshdesk-whatsapp-integration", permanent: true },
  { source: "/product/leadsquared-whatsapp-integration", destination: "/leadsquared-whatsapp-integration", permanent: true },
  { source: "/product/google-sheets-whatsapp-integration", destination: "/google-sheets-whatsapp-integration", permanent: true },
  { source: "/product/hubspot-whatsapp-integration", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/7-wa-deck-alternatives-which-one-should-you-choose", destination: "/", permanent: true },
  { source: "/blog/boost-sales-efficiency-eazybes-hubspot-whatsapp-integration", destination: "/", permanent: true },
  { source: "/blog/boost-your-crm-efficiency-a-comprehensive-guide-to-integrating-whatsapp-with-hubspot-using-eazybe", destination: "/", permanent: true },
  { source: "/blog/boost-your-sales-with-zoho-crm-whatsapp-integration", destination: "/zoho-whatsapp-integration", permanent: true },
  { source: "/blog/craft-attractive-messages-for-customers-on-whatsapp", destination: "/", permanent: true },
  { source: "/blog/essential-glossary-of-artificial-intelligence-ai-terms", destination: "/", permanent: true },
  { source: "/blog/boost-your-sales-process-with-these-15-automation-tools", destination: "/", permanent: true },
  { source: "/blog/15-best-ai-drive-sales-tool-for-b2c-companies-using-whatsapp-business-2025", destination: "/", permanent: true },
  { source: "/blog/effective-approaches-for-balancing-customer-retention-acquisition", destination: "/", permanent: true },
  { source: "/blog/15-best-ai-driven-sales-tools-for-b2c-companies", destination: "/", permanent: true },
  { source: "/blog/whatsapp-vs-whatsapp-business-vs-whatsapp-api", destination: "/", permanent: true },
  { source: "/blog/create-whatsapp-channel-boost-communication-strategy", destination: "/", permanent: true },
  { source: "/blog/beginners-guide-mastering-whatsapp-crm-for-beginners", destination: "/", permanent: true },
  { source: "/blog/10-ways-whatsapp-crm-can-revolutionize-your-business", destination: "/", permanent: true },
  { source: "/blog/discover-10-whatsapp-hacks-for-2025-you-need-now", destination: "/", permanent: true },
  { source: "/blog/chatgpt-4-0-on-whatsapp-eazybe-extension-for-ai-sales", destination: "/", permanent: true },
  { source: "/blog/connect-better-the-easy-way-to-whatsapp-web-login", destination: "/", permanent: true },
  { source: "/blog/whatsapp-business-vs-whatsapp-vs-whatsapp-api", destination: "/", permanent: true },
  { source: "/blog/10-whatsapp-crm-hacks-for-explosive-sales-results", destination: "/", permanent: true },
  { source: "/blog/all-you-need-to-know-about-zoho-crm", destination: "/", permanent: true },
  { source: "/blog/9-ways-to-use-whatsapp-for-customer-service-2023", destination: "/", permanent: true },
  { source: "/blog/chatgpt-4-0-on-whatsapp-install-eazybe-send-ai-whatsapp-messages", destination: "/", permanent: true },
  { source: "/blog/boost-your-workflow-with-webhooks-integration-with-whatsapp", destination: "/", permanent: true },
  { source: "/blog/guide-to-building-an-effective-b2b-sales-strategy", destination: "/", permanent: true },
  { source: "/blog/mastering-b2b-sales-prospecting-a-beginners-guide", destination: "/", permanent: true },
  { source: "/blog/discover-the-best-whatsapp-business-api-alternatives", destination: "/", permanent: true },
  { source: "/blog/b2b-account-management-using-whatsapp-groups-and-eazybe-integrationv", destination: "/", permanent: true },
  { source: "/blog/customer-retention-loyalty-key-differences-explained", destination: "/", permanent: true },
  { source: "/blog/exploring-zoho-crm-cost-plans-features-and-add-ons", destination: "/zoho-whatsapp-integration", permanent: true },
  { source: "/blog/exploring-the-best-alternatives-to-whatsup-plus", destination: "/", permanent: true },
  { source: "/blog/integrate-hubspot-with-whatsapp-easiest-method", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/whatsapp-marketing-with-100-accurate-results-skyrocket-your-sales-with-eazybe", destination: "/", permanent: true },
  { source: "/blog/save-a-contact-to-phone-using-eazybe-extension", destination: "/", permanent: true },
  { source: "/blog/how-to-use-chatgpt-on-whatsapp", destination: "/", permanent: true },
  { source: "/blog/get-organized-with-hubspot-free-crm-start-now", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/apply-for-green-tick-on-whatsapp-business", destination: "/", permanent: true },
  { source: "/blog/google-calendar-on-whatsapp-eazybe-extension-guide", destination: "/google-calendar-whatsapp-integration", permanent: true },
  { source: "/blog/hubspot-whatsapp-integration-guide-seamless-connection", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/how-ai-crm-whatsapp-can-revolutionize-your-business-in-2025", destination: "/", permanent: true },
  { source: "/blog/add-whatsapp-on-your-wordpress-website", destination: "/", permanent: true },
  { source: "/blog/create-marketing-sales-funnel-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/blog/how-hubspot-hit-100m--and-how-you-can-too", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/eazybe-help-you-increase-your-covid-era-remote-working-productivity", destination: "/", permanent: true },
  { source: "/blog/unlimited-data-on-whatsapp-with-this-trick-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/blog/elevate-results-whatsapp-integration-for-crm-success", destination: "/", permanent: true },
  { source: "/blog/elevate-sales-team-performance-with-crm-whatsapp-integration", destination: "/", permanent: true },
  { source: "/blog/eazybe-chrome-extension-install-make-your-whatsapp-incredibly-professional", destination: "/", permanent: true },
  { source: "/blog/do-you-use-whatsapp-effectively-for-sales", destination: "/", permanent: true },
  { source: "/blog/eazybes-bitrix24-integration-transforming-customer-management", destination: "/bitrix24-whatsapp-integration", permanent: true },
  { source: "/blog/ditch-wa-deck-top-7-alternatives-for-better-whatsapp-experience", destination: "/", permanent: true },
  { source: "/blog/how-to-edit-andriod-contacts-on-whatsapp-without-leaving-the-app", destination: "/", permanent: true },
  { source: "/blog/get-whatsapp-green-tick-verification-easiest-method", destination: "/", permanent: true },
  { source: "/blog/do-team-management-on-whatsapp-use-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/blog/how-small-businesses-can-grow-in-2022", destination: "/", permanent: true },
  { source: "/blog/leadsquared-crm-the-ultimate-sales-marketing-solution", destination: "/leadsquared-whatsapp-integration", permanent: true },
  { source: "/blog/revolutionizing-crm-through-whatsapp-zoho-integration-free-using-eazybe", destination: "/zoho-whatsapp-integration", permanent: true },
  { source: "/blog/send-message-without-saving-their-number-on-whatsapp", destination: "/", permanent: true },
  { source: "/blog/make-your-texts-stand-out-with-these-whatsapp-message-tricks", destination: "/", permanent: true },
  { source: "/blog/organize-chats-on-whatsapp-whatsapp-look-clean-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/blog/hubspot-crm-cost-what-you-need-to-know", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/hubspot-as-a-crm-the-key-to-a-streamlined-sales-process", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/manage-your-hubspot-crm-on-whatsapp-with-eazybe", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/how-whatapp-will-take-over-email-by-2030", destination: "/", permanent: true },
  { source: "/blog/create-a-chat-gpt-3-ai-chatbot-on-whatsapp", destination: "/", permanent: true },
  { source: "/blog/travel-agency-crm-benefits-whatsapp-hubspot-integration", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/implementing-whatsapp-quick-replies-for-your-team", destination: "/features/quick-reply", permanent: true },
  { source: "/blog/personalized-marketing-with-whatsapp", destination: "/", permanent: true },
  { source: "/blog/sales-are-now-switching-to-messages", destination: "/", permanent: true },
  { source: "/blog/how-to-easily-transfer-whatsapp-chats-from-android-to-iphone", destination: "/", permanent: true },
  { source: "/blog/boost-sales-with-hubspot-whatsapp-integration", destination: "/", permanent: true },
  { source: "/blog/boost-loyalty-improve-customer-retention-strategies", destination: "/", permanent: true },
  { source: "/blog/how-to-set-up-and-integrate-whatsapp-webhook-2-methods", destination: "/", permanent: true },
  { source: "/blog/difference-between-whatsapp-web-whatsapp-business-api", destination: "/", permanent: true },
  { source: "/blog/expert-tips-for-successful-sales-recruitment", destination: "/", permanent: true },
  { source: "/blog/install-chrome-extension-in-microsoft-edge-use-this-hack", destination: "/", permanent: true },
  { source: "/blog/navigating-top-challenges-crm-users-will-face-in-2025", destination: "/", permanent: true },
  { source: "/blog/hubspot-crm-whatsapp-integration", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/manage-google-calendar-through-eazybe-whatsapp-chrome-extensions", destination: "/google-calendar-whatsapp-integration", permanent: true },
  { source: "/blog/close-your-ongoing-sales-with-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/blog/best-tool-to-close-almost-all-your-deals", destination: "/", permanent: true },
  { source: "/blog/whatsapp-polls-their-benefits-and-best-practices", destination: "/", permanent: true },
  { source: "/blog/use-google-sheets-on-whatsapp", destination: "/google-sheets-whatsapp-integration", permanent: true },
  { source: "/blog/sales-closing-phrases-to-avoid", destination: "/", permanent: true },
  { source: "/blog/unlocking-the-benefits-of-crm-systems-for-your-business", destination: "/", permanent: true },
  { source: "/blog/quick-steps-to-unblock-your-whatsapp-business-account", destination: "/", permanent: true },
  { source: "/blog/synchronizing-whatsapp-conversations-with-hubspot-crm", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/whatsapp-update-now-send-files-upto-2gb-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/blog/the-perfect-sales-close-plan-eazybe-chrome-extension", destination: "/", permanent: true },
  { source: "/blog/whatsapp-companion-mode-how-to-use-whatsapp-on-two-phones", destination: "/", permanent: true },
  { source: "/blog/unlocking-hubspot-whatsapp-integration-free-tips", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/whatsapp-business-api-everything-you-need-to-see", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/7-best-alternative-of-cooby-elevate-your-experience", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/what-is-customer-retention-strategies-and-metrics", destination: "/", permanent: true },
  { source: "/blog/whatsapp-hubspot-integration-how-to-sync-whatsapp-chats-with-hubspot", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/the-complete-guide-to-pricing-for-whatsapp-business-api-2023", destination: "/", permanent: true },
  { source: "/blog/unlocking-the-power-of-whatsapp-ads-tips-for-successful-campaigns", destination: "/", permanent: true },
  { source: "/blog/whatsapp-catalogue-everything-you-need-to-know-in-2023", destination: "/", permanent: true },
  { source: "/blog/whatsapp-community-know-everything-about-the-latest-update", destination: "/", permanent: true },
  { source: "/blog/streamlining-customer-communication-integrating-whatsapp-with-hubspot", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/the-future-of-crm-top-integration-tools-transforming-customer-relationship-management-in-2024", destination: "/", permanent: true },
  { source: "/blog/unlock-productivity-with-tasks-hubspot-whatsapp-integration", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/blog/use-these-7-proven-strategies-to-grow-your-business", destination: "/", permanent: true },
  { source: "/blog/streamlining-crm-with-whatsapp-web-integration", destination: "/", permanent: true },
  { source: "/blog/whatsapp-otp-how-do-you-send-an-otp-on-whatsapp", destination: "/", permanent: true },
  { source: "/blog/customer-support-freshdesk-and-whatsapp-integration-eazybe", destination: "/freshdesk-whatsapp-integration", permanent: true },
  { source: "/blog/the-ultimate-alternative-to-cooby-kiosk-unipile-and-more", destination: "/", permanent: true },
  { source: "/blog/top-whatsapp-alternatives-2024-find-your-perfect-match", destination: "/", permanent: true },
  { source: "/blog/unveiling-the-preference-for-whatsapp-over-sms-emails", destination: "/", permanent: true },
  { source: "/blog/whatsapp-otp-how-to-send-otp-with-whatsapp-in-2023", destination: "/", permanent: true },
  { source: "/blog/the-perfect-match-whatsapp-meets-hubspot-for-seamless-crm", destination: "/", permanent: true },
  { source: "/blog/whatsapp-chatbot-for-business-how-to-get-it-for-free-in-2023", destination: "/", permanent: true },
  { source: "/blog/top-3-chrome-extensions-that-you-must-install-right-now", destination: "/", permanent: true },
  { source: "/blog/business-guide-build-sales-team-high-performance", destination: "/", permanent: true },
  { source: "/blog/the-ultimate-crm-buying-guide-how-to-choose-the-right-crm-for-your-sales-team-in-2025", destination: "/", permanent: true },
  { source: "/blog/communities-in-whatsapp-interesting-ways-to-use-them", destination: "/", permanent: true },
  { source: "/blog/whatsapp-hacks-how-to-message-without-saving-contact", destination: "/", permanent: true },
  { source: "/blog/the-power-of-ai-in-sales-introducing-eazybes-revolutionary-ai-assistant-for-2024", destination: "/", permanent: true },
  { source: "/blog/catalog-in-whatsapp-business-how-to-make-and-maintain-it", destination: "/", permanent: true },
  { source: "/blog/step-by-step-guide-view-names-on-whatsapp-without-saving-numbers", destination: "/", permanent: true },
  { source: "/blog/start-chat-without-saving-the-number-on-whatsapp", destination: "/", permanent: true },
  { source: "/blog/test-blog", destination: "/", permanent: true },
  { source: "/blog/will-ai-replace-sales-agents-heres-what-the-latest-data-and-trends-reveal", destination: "/", permanent: true },
  { source: "/blog/zoho-crm-free-your-ultimate-crm-solution", destination: "/zoho-whatsapp-integration", permanent: true },
  { source: "/blog/whatsapp-verification-call-stopped-the-impact-solutions-and-account-security", destination: "/", permanent: true },
  { source: "/post/how-to-easily-transfer-whatsapp-to-new-number", destination: "/", permanent: true },
  { source: "/post/how-to-send-bulk-messages-on-whatsapp-tips-for-effective-campaigns", destination: "/", permanent: true },
  { source: "/post/whatsapp-crm-integration-powerful-tool-for-enhancing-customer-relationships", destination: "/", permanent: true },
  { source: "/post/how-to-manage-your-team-effectively-on-whatsapp-eazybes-chrome-extension", destination: "/", permanent: true },
  { source: "/post/how-to-unlock-productivity-with-whatsapp-for-small-businesses", destination: "/", permanent: true },
  { source: "/post/hubspot-crm-pricing-is-it-worth-the-investment-for-your-business", destination: "/hubspot-whatsapp-integration", permanent: true },
  { source: "/post/maximize-business-efficiency-with-whatsapp-crm-integration", destination: "/", permanent: true },
  { source: "/post/the-perfect-whatsapp-message-template-for-increasing-sales", destination: "/", permanent: true },
  { source: "/post/how-to-recover-deleted-whatsapp-messages-on-ios-and-android", destination: "/", permanent: true },
  { source: "/post/how-to-export-whatsapp-chat-a-comprehensive-guide", destination: "/", permanent: true },
  { source: "/post/how-to-schedule-messages-on-whatsapp-a-simple-guide", destination: "/", permanent: true },
  { source: "/post/how-to-setup-a-whatsapp-chatbot-for-your-business", destination: "/", permanent: true },
  { source: "/post/the-ultimate-guide-to-using-whatsapp-automation-for-sales", destination: "/", permanent: true },
  { source: "/br/blog/synchronizing-whatsapp-conversations-with-hubspot-crm", destination: "/br/hubspot-whatsapp-integration", permanent: true },
  { source: "/br/blog/complete-guide-whatsapp-crm-integration", destination: "/br/integrations", permanent: true },
  { source: "/br/blog/use-google-sheets-on-whatsapp", destination: "/br/blog", permanent: true },
  { source: "/br/blog/beginners-guide-mastering-whatsapp-crm-for-beginners", destination: "/br/blog", permanent: true },
  { source: "/br/blog/connect-better-the-easy-way-to-whatsapp-web-login", destination: "/br/blog", permanent: true },
  { source: "/br/blog/difference-between-whatsapp-web-whatsapp-business-api", destination: "/br/blog", permanent: true },
  { source: "/br/blog/the-ultimate-crm-buying-guide-how-to-choose-the-right-crm-for-your-sales-team-in-2025", destination: "/br/blog", permanent: true },
  { source: "/br/blog/whatsapp-otp-how-to-send-otp-with-whatsapp-in-2023", destination: "/br/blog", permanent: true },
  { source: "/br/blog/unveiling-the-preference-for-whatsapp-over-sms-emails", destination: "/br/blog", permanent: true },
  { source: "/br/blog/15-best-ai-drive-sales-tool-for-b2c-companies-using-whatsapp-business-2025", destination: "/br/blog", permanent: true },
  { source: "/br/blog/boost-sales-with-hubspot-whatsapp-integration", destination: "/br/hubspot-whatsapp-integration", permanent: true },
  { source: "/br/blog-pt/organize-se-com-hubspot-free-crm-comece-agora", destination: "/br/blog", permanent: true },
  { source: "/br/blog/hubspot-crm-whatsapp-integration", destination: "/br/hubspot-whatsapp-integration", permanent: true },
  { source: "/br/blog/create-a-chat-gpt-3-ai-chatbot-on-whatsapp", destination: "/br/blog", permanent: true },
  { source: "/br/blog/10-ways-whatsapp-crm-can-revolutionize-your-business", destination: "/br/blog", permanent: true },
  { source: "/br/blog/elevate-sales-team-performance-with-crm-whatsapp-integration", destination: "/br/blog", permanent: true },
  { source: "/br/blog/the-future-of-crm-top-integration-tools-transforming-customer-relationship-management-in-2024", destination: "/br/blog", permanent: true },
  { source: "/br/blog/boost-loyalty-improve-customer-retention-strategies", destination: "/br/blog", permanent: true },
  { source: "/br/blog/the-complete-guide-to-pricing-for-whatsapp-business-api-2023", destination: "/br/blog", permanent: true },
  { source: "/br/blog/whatsapp-companion-mode-how-to-use-whatsapp-on-two-phones", destination: "/br/blog", permanent: true },
  { source: "/br/blog/get-organized-with-hubspot-free-crm-start-now", destination: "/br/hubspot-whatsapp-integration", permanent: true },
  { source: "/br/blog/best-tool-to-close-almost-all-your-deals", destination: "/br/blog", permanent: true },
  { source: "/br/integrations-es", destination: "/br/integrations", permanent: true },
  { source: "/br/blog-pt/catalogo-do-whatsapp-tudo-o-que-voce-precisa-saber-em-2023", destination: "/br/blog", permanent: true },
  { source: "/br/blog-es/5-alternativas-a-wa-web-plus", destination: "/br/blog", permanent: true },
  { source: "/br/pricing-es", destination: "/br/pricing", permanent: true },
  { source: "/br/integrations-pt", destination: "/br/integrations", permanent: true },
  { source: "/br/privacy-pt", destination: "/br/privacy", permanent: true },
  { source: "/br/salesforce-es", destination: "/br/salesforce-whatsapp-integration", permanent: true },
  { source: "/br/pricing-pt", destination: "/br/pricing", permanent: true },
  { source: "/br/hubspot-es", destination: "/br/hubspot-whatsapp-integration", permanent: true },
  { source: "/br/privacy-es", destination: "/br/privacy", permanent: true },
  { source: "/br/terms-of-service-es", destination: "/br/terms", permanent: true },
  { source: "/br/blog-pt/frases-de-fechamento-de-vendas-a-evitar", destination: "/br/blog", permanent: true },
  { source: "/br/blog-pt/o-guia-definitivo-para-backup-da-caixa-de-entrada-da-equipe-do-whatsapp", destination: "/br/blog", permanent: true },
  { source: "/br/blog-pt/api-do-whatsapp-x-whatsapp-web-power", destination: "/br/blog", permanent: true },
  { source: "/br/blog/5-wa-web-plus-alternatives-best-whatsapp-chrome-extensions", destination: "/br/blog", permanent: true },
  { source: "/br/blog/beginners-guide-mastering-whatsapp-automation-for-sales", destination: "/br/blog", permanent: true },
  { source: "/br/blog/the-power-of-ai-in-sales-introducing-eazybes-revolutionary-ai-assistant-for-2024", destination: "/br/blog", permanent: true },
  { source: "/br/blog/start-chat-without-saving-the-number-on-whatsapp", destination: "/br/blog", permanent: true },
  { source: "/br/blog/whatsapp-broadcast-message-everything-you-need-to-know", destination: "/br/blog", permanent: true },
  { source: "/br/blog/do-you-use-whatsapp-effectively-for-sales", destination: "/br/blog", permanent: true },
  { source: "/br/blog-pt/integracao-do-whatsapp-hubspot-como-sincronizar-bate-papos-do-whatsapp-com-o-hubspot", destination: "/br/blog", permanent: true },
  { source: "/br/terms-of-service-pt", destination: "/br/terms", permanent: true },
  { source: "/br/blog-es/que-son-las-comunidades-en-whatsapp-formas-interesantes-de-utilizarlos", destination: "/br/blog", permanent: true },
  { source: "/br/blog-pt/guia-completo-do-whatsapp-api-vs-whatsapp-web", destination: "/br/blog", permanent: true },
  { source: "/br/blog/whatsapp-business-groups-and-broadcast-lists-to-reach-your-customers", destination: "/br/blog", permanent: true },
  { source: "/br/blog/guide-to-building-an-effective-b2b-sales-strategy", destination: "/br/blog", permanent: true },
  { source: "/br/blog/set-reminders-on-whatsapp-with-eazybe-chrome-extension", destination: "/br/blog", permanent: true },
  { source: "/br/blog/how-whatsapp-reminder-makes-you-productive", destination: "/br/blog", permanent: true },
  { source: "/br/blog/zoho-crm-free-your-ultimate-crm-solution", destination: "/br/zoho-whatsapp-integration", permanent: true },
]
